[project]
name = "pivatolorissistemi2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "plotly>=5.24.1",
    "polars>=1.17.1",
    "streamlit>=1.41.1",
]
